CREATE OR REPLACE PACKAGE PKG_EMPLOYEE AS

    PROCEDURE SP_REGISTER_EMPLOYEE(
        P_EMP_ID          IN TBL_EMPLOYEE.EMP_ID%TYPE,
        P_DEA_ID          IN TBL_EMPLOYEE.DEA_ID%TYPE,
        P_EMP_NAME        IN TBL_EMPLOYEE.EMP_NAME%TYPE,
        P_EMP_PHONE       IN TBL_EMPLOYEE.EMP_PHONE%TYPE,
        P_EMP_SALARY      IN TBL_EMPLOYEE.EMP_SALARY%TYPE,
        P_EMP_HIRE_DATE   IN TBL_EMPLOYEE.EMP_HIRE_DATE%TYPE,
        P_EMP_ROLE        IN TBL_EMPLOYEE.EMP_ROLE%TYPE DEFAULT 'seller'
    );

    PROCEDURE SP_UPDATE_EMPLOYEE(
        P_EMP_ID          IN TBL_EMPLOYEE.EMP_ID%TYPE,
        P_EMP_NAME        IN TBL_EMPLOYEE.EMP_NAME%TYPE DEFAULT NULL,
        P_EMP_PHONE       IN TBL_EMPLOYEE.EMP_PHONE%TYPE DEFAULT NULL,
        P_EMP_SALARY      IN TBL_EMPLOYEE.EMP_SALARY%TYPE DEFAULT NULL
    );

    PROCEDURE SP_DISABLE_EMPLOYEE(P_EMP_ID IN TBL_EMPLOYEE.EMP_ID%TYPE);
    
    FUNCTION FN_EMPLOYEE_EXIST(P_EMP_ID IN TBL_EMPLOYEE.EMP_ID%TYPE)
    RETURN BOOLEAN;

    FUNCTION FN_GET_EMPLOYEE_BY_ID(P_EMP_ID IN TBL_EMPLOYEE.EMP_ID%TYPE)
    RETURN SYS_REFCURSOR;
    
    FUNCTION FN_GET_EMPLOYEES_BY_DEALERSHIP(P_DEA_ID IN TBL_EMPLOYEE.DEA_ID%TYPE)
    RETURN SYS_REFCURSOR;

    FUNCTION FN_GET_ALL_EMPLOYEES
    RETURN SYS_REFCURSOR;
    
    FUNCTION FN_GET_EMPLOYEES_ABOVE_AVG 
    RETURN SYS_REFCURSOR;

END PKG_EMPLOYEE;
/

CREATE OR REPLACE PACKAGE BODY PKG_EMPLOYEE AS

    PROCEDURE SP_REGISTER_EMPLOYEE(
        P_EMP_ID          IN TBL_EMPLOYEE.EMP_ID%TYPE,
        P_DEA_ID         IN TBL_EMPLOYEE.DEA_ID%TYPE,
        P_EMP_NAME        IN TBL_EMPLOYEE.EMP_NAME%TYPE,
        P_EMP_PHONE       IN TBL_EMPLOYEE.EMP_PHONE%TYPE,
        P_EMP_SALARY      IN TBL_EMPLOYEE.EMP_SALARY%TYPE,
        P_EMP_HIRE_DATE   IN TBL_EMPLOYEE.EMP_HIRE_DATE%TYPE,
        P_EMP_ROLE        IN TBL_EMPLOYEE.EMP_ROLE%TYPE DEFAULT 'seller'
    )
    IS
    BEGIN
    
        IF (FN_EMPLOYEE_EXIST(P_EMP_ID)) THEN
            RAISE_APPLICATION_ERROR(-20301,'Empleado ya registrado.');
        END IF;
        
        IF NOT(PKG_DEALERSHIP.FN_DEALERSHIP_EXIST(P_DEA_ID))THEN
            RAISE_APPLICATION_ERROR(-20311,'Concesionaria no registrada.');
        END IF;
        
        PKG_VALIDATIONS.VALIDATE_NAME(P_EMP_NAME);
        PKG_VALIDATIONS.VALIDATE_PHONE(P_EMP_PHONE);
        PKG_VALIDATIONS.VALIDATE_ROLE(P_EMP_ID,P_DEA_ID, P_EMP_ROLE);
        PKG_VALIDATIONS.VALIDATE_DATE(P_EMP_HIRE_DATE);
        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_EMP_SALARY,'Salary');

        INSERT INTO TBL_EMPLOYEE (EMP_ID, DEA_ID, EMP_NAME, EMP_PHONE, EMP_SALARY, EMP_HIRE_DATE, EMP_ROLE, EMP_STATE)
        VALUES (P_EMP_ID, P_DEA_ID, TRIM(P_EMP_NAME), P_EMP_PHONE, P_EMP_SALARY, P_EMP_HIRE_DATE, TRIM(LOWER(P_EMP_ROLE)),'active');

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR(-20900,'Violacion de PK o UNIQUE.');

    END SP_REGISTER_EMPLOYEE;

    PROCEDURE SP_UPDATE_EMPLOYEE(
        P_EMP_ID          IN TBL_EMPLOYEE.EMP_ID%TYPE,
        P_EMP_NAME        IN TBL_EMPLOYEE.EMP_NAME%TYPE DEFAULT NULL,
        P_EMP_PHONE       IN TBL_EMPLOYEE.EMP_PHONE%TYPE DEFAULT NULL,
        P_EMP_SALARY      IN TBL_EMPLOYEE.EMP_SALARY%TYPE DEFAULT NULL
    ) 
    IS
        V_STATE TBL_EMPLOYEE.EMP_STATE%TYPE;
    BEGIN
        IF NOT(FN_EMPLOYEE_EXIST(P_EMP_ID)) THEN
            RAISE_APPLICATION_ERROR(-20302,'Empleado no encontrado.');
        END IF;
        SELECT EMP_STATE INTO V_STATE FROM TBL_EMPLOYEE WHERE EMP_ID = P_EMP_ID;

        PKG_VALIDATIONS.VALIDATE_STATE(V_STATE);
        PKG_VALIDATIONS.VALIDATE_PHONE(P_EMP_PHONE);
        PKG_VALIDATIONS.VALIDATE_NAME(P_EMP_NAME);
        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_EMP_SALARY,'Salary');

        UPDATE TBL_EMPLOYEE
        SET
            EMP_NAME  = NVL(TRIM(P_EMP_NAME), EMP_NAME),
            EMP_PHONE = NVL(P_EMP_PHONE, EMP_PHONE),
            EMP_SALARY = NVL(P_EMP_SALARY, EMP_SALARY)
        WHERE EMP_ID = P_EMP_ID;

    END SP_UPDATE_EMPLOYEE;

    PROCEDURE SP_DISABLE_EMPLOYEE(P_EMP_ID IN TBL_EMPLOYEE.EMP_ID%TYPE) 
    IS
        V_SALES NUMBER; 
    BEGIN
        IF NOT (FN_EMPLOYEE_EXIST(P_EMP_ID)) THEN
            RAISE_APPLICATION_ERROR(-20302,'Empleado no encontrado.');
        END IF;
        SELECT COUNT(*) INTO V_SALES FROM TBL_SALE WHERE EMP_ID = P_EMP_ID AND SALE_STATUS = 'inprogress';

        IF (V_SALES > 0) THEN
            RAISE_APPLICATION_ERROR(-20303,'Empleado con ventas en progreso.');
        END IF;

        UPDATE TBL_EMPLOYEE SET EMP_STATE = 'inactive' WHERE EMP_ID = P_EMP_ID;

    END SP_DISABLE_EMPLOYEE;

    FUNCTION FN_EMPLOYEE_EXIST(P_EMP_ID IN TBL_EMPLOYEE.EMP_ID%TYPE)
    RETURN BOOLEAN
    IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM TBL_EMPLOYEE WHERE EMP_ID = P_EMP_ID;
        
        RETURN V_COUNT > 0;
        
    END FN_EMPLOYEE_EXIST;

    FUNCTION FN_GET_EMPLOYEE_BY_ID(P_EMP_ID IN TBL_EMPLOYEE.EMP_ID%TYPE)
    RETURN SYS_REFCURSOR
    IS
        V_CURSOR SYS_REFCURSOR;
    BEGIN
        IF NOT(FN_EMPLOYEE_EXIST(P_EMP_ID)) THEN
            RAISE_APPLICATION_ERROR(-20302,'Empleado no encontrado.');
        END IF;

        OPEN V_CURSOR FOR
            SELECT *
            FROM TBL_EMPLOYEE
            WHERE EMP_ID = P_EMP_ID;

        RETURN V_CURSOR;
    END;

    FUNCTION FN_GET_EMPLOYEES_BY_DEALERSHIP(P_DEA_ID IN TBL_EMPLOYEE.DEA_ID%TYPE)
    RETURN SYS_REFCURSOR
    IS
        V_EMPLOYEES SYS_REFCURSOR;
    BEGIN
        OPEN V_EMPLOYEES FOR
            SELECT * FROM TBL_EMPLOYEE WHERE DEA_ID = P_DEA_ID;
    RETURN V_EMPLOYEES;
    END FN_GET_EMPLOYEES_BY_DEALERSHIP;
    
    FUNCTION FN_GET_ALL_EMPLOYEES
    RETURN SYS_REFCURSOR
    IS
        V_CURSOR SYS_REFCURSOR;
    BEGIN
        OPEN V_CURSOR FOR
            SELECT * FROM TBL_EMPLOYEE
            ORDER BY EMP_SALARY DESC;

        RETURN V_CURSOR;
    END FN_GET_ALL_EMPLOYEES;
    
    FUNCTION FN_GET_EMPLOYEES_ABOVE_AVG 
    RETURN SYS_REFCURSOR
    IS
        V_EMPLOYEES SYS_REFCURSOR;
    BEGIN
        OPEN V_EMPLOYEES FOR
            SELECT * FROM TBL_EMPLOYEE WHERE EMP_SALARY>(SELECT AVG(EMP_SALARY) FROM TBL_EMPLOYEE);
    RETURN V_EMPLOYEES;
    END FN_GET_EMPLOYEES_ABOVE_AVG;

END PKG_EMPLOYEE;
/