/*secuencia de generacion de id*/
CREATE SEQUENCE SEQ_SALESGOAL START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE PACKAGE PKG_SALESGOAL AS

    PROCEDURE SP_REGISTER_SALESGOAL(
        P_SGL_ID             OUT TBL_SALESGOAL.SGL_ID%TYPE,  
        P_EMP_ID             IN TBL_SALESGOAL.EMP_ID%TYPE DEFAULT NULL,
        P_DEA_ID             IN TBL_SALESGOAL.DEA_ID%TYPE,
        P_SGL_GOAL_TYPE           IN TBL_SALESGOAL.SGL_GOAL_TYPE%TYPE,
        P_SGL_TARGET_VALUE   IN TBL_SALESGOAL.SGL_TARGET_VALUE%TYPE,
        P_SGL_START_DATE     IN TBL_SALESGOAL.SGL_START_DATE%TYPE
    );

    PROCEDURE SP_UPDATE_SALESGOAL(
        P_SGL_ID             IN TBL_SALESGOAL.SGL_ID%TYPE,
        P_SGL_TARGET_VALUE   IN TBL_SALESGOAL.SGL_TARGET_VALUE%TYPE,
        P_SGL_GOAL_TYPE      IN TBL_SALESGOAL.SGL_GOAL_TYPE%TYPE
    );

    PROCEDURE SP_DISABLE_SALESGOAL(P_SGL_ID IN TBL_SALESGOAL.SGL_ID%TYPE);

    PROCEDURE SP_COMPLETE_SALESGOAL(P_SGL_ID IN TBL_SALESGOAL.SGL_ID%TYPE);
    
    FUNCTION FN_SALESGOAL_EXIST(P_SGL_ID IN TBL_SALESGOAL.SGL_ID%TYPE)
    RETURN BOOLEAN;

    FUNCTION FN_GET_SALESGOAL_BY_ID(P_SGL_ID IN TBL_SALESGOAL.SGL_ID%TYPE)
    RETURN TBL_SALESGOAL%ROWTYPE;

    FUNCTION FN_GET_ALL_SALESGOALS
    RETURN SYS_REFCURSOR;

    FUNCTION FN_GET_SALESGOALS_BY_STATE(P_SGL_STATE IN TBL_SALESGOAL.SGL_STATE%TYPE)
    RETURN SYS_REFCURSOR;

END PKG_SALESGOAL;
/

CREATE OR REPLACE PACKAGE BODY PKG_SALESGOAL AS

    PROCEDURE SP_REGISTER_SALESGOAL(
        P_SGL_ID             OUT TBL_SALESGOAL.SGL_ID%TYPE,
        P_EMP_ID             IN TBL_SALESGOAL.EMP_ID%TYPE DEFAULT NULL,
        P_DEA_ID             IN TBL_SALESGOAL.DEA_ID%TYPE,
        P_SGL_GOAL_TYPE      IN TBL_SALESGOAL.SGL_GOAL_TYPE%TYPE,
        P_SGL_TARGET_VALUE   IN TBL_SALESGOAL.SGL_TARGET_VALUE%TYPE,
        P_SGL_START_DATE     IN TBL_SALESGOAL.SGL_START_DATE%TYPE
        )
    IS
        V_COUNT NUMBER;
    BEGIN

        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_SGL_TARGET_VALUE,'P_SGL_TARGET_VALUE');
        PKG_VALIDATIONS.VALIDATE_DATE(P_SGL_START_DATE);
        PKG_VALIDATIONS.VALIDATE_GOAL_TYPE(P_SGL_GOAL_TYPE);
        
        IF NOT(PKG_DEALERSHIP.FN_DEALERSHIP_EXIST(P_DEA_ID))THEN
            RAISE_APPLICATION_ERROR(-20606,'Concesionaria no encontrada');
        END IF;
        
        IF(P_EMP_ID IS NOT NULL)THEN
            IF NOT(PKG_EMPLOYEE.FN_EMPLOYEE_EXIST(P_EMP_ID))THEN
                RAISE_APPLICATION_ERROR(-20607,'Empleado no encontrado');
            END IF;
        END IF;

        SELECT COUNT(*) INTO V_COUNT FROM TBL_SALESGOAL WHERE DEA_ID = P_DEA_ID AND LOWER(TRIM(SGL_STATE)) = 'active';
        IF(V_COUNT > 0)THEN
            RAISE_APPLICATION_ERROR(-20602,'No se pueden asignar 2 metas activas a la misma concesionaria');
        END IF;

        SELECT COUNT(*) INTO V_COUNT FROM TBL_SALESGOAL WHERE EMP_ID = P_EMP_ID AND LOWER(TRIM(SGL_STATE)) = 'active';
        IF(V_COUNT > 0)THEN 
            RAISE_APPLICATION_ERROR(-20603,'No se pueden asignar 2 metas activas al mismo empleado');
        END IF;

        INSERT INTO TBL_SALESGOAL (SGL_ID,EMP_ID,DEA_ID,SGL_GOAL_TYPE,SGL_TARGET_VALUE,SGL_START_DATE,SGL_STATE)
        VALUES (SEQ_SALESGOAL.NEXTVAL,P_EMP_ID,P_DEA_ID,LOWER(TRIM(P_SGL_GOAL_TYPE)),P_SGL_TARGET_VALUE,P_SGL_START_DATE,'active') RETURNING SGL_ID INTO P_SGL_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20900,'Violacion de PK o UNIQUE.');

    END SP_REGISTER_SALESGOAL;

    PROCEDURE SP_UPDATE_SALESGOAL(
        P_SGL_ID             IN TBL_SALESGOAL.SGL_ID%TYPE,
        P_SGL_TARGET_VALUE   IN TBL_SALESGOAL.SGL_TARGET_VALUE%TYPE,
        P_SGL_GOAL_TYPE      IN TBL_SALESGOAL.SGL_GOAL_TYPE%TYPE
    )
    IS
    BEGIN

        IF NOT(FN_SALESGOAL_EXIST(P_SGL_ID))THEN
            RAISE_APPLICATION_ERROR(-20603,'Meta no encontrada');
        END IF;

        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_SGL_TARGET_VALUE,'P_SGL_TARGET_VALUE');

        IF (P_SGL_GOAL_TYPE IS NOT NULL) THEN
            PKG_VALIDATIONS.VALIDATE_GOAL_TYPE(P_SGL_GOAL_TYPE);
        END IF;

        UPDATE TBL_SALESGOAL
        SET
            SGL_TARGET_VALUE =P_SGL_TARGET_VALUE,
            SGL_GOAL_TYPE = LOWER(TRIM(P_SGL_GOAL_TYPE))
        WHERE SGL_ID = P_SGL_ID;

    END SP_UPDATE_SALESGOAL;

    PROCEDURE SP_DISABLE_SALESGOAL(
        P_SGL_ID IN TBL_SALESGOAL.SGL_ID%TYPE
        )
    IS
        V_STATE TBL_SALESGOAL.SGL_STATE%TYPE;
    BEGIN
    
        IF NOT(FN_SALESGOAL_EXIST(P_SGL_ID))THEN
            RAISE_APPLICATION_ERROR(-20603,'Meta no encontrada');
        END IF;

        SELECT SGL_STATE INTO V_STATE FROM TBL_SALESGOAL WHERE SGL_ID = P_SGL_ID;

        PKG_VALIDATIONS.VALIDATE_SALESGOAL_STATE(V_STATE);

        IF (LOWER(TRIM(V_STATE)) = 'complete') THEN
            RAISE_APPLICATION_ERROR(-20605,'La meta ya fue completada, no se puede inactivar');
        END IF;

        UPDATE TBL_SALESGOAL SET SGL_STATE = 'inactive' WHERE SGL_ID = P_SGL_ID;

    END SP_DISABLE_SALESGOAL;

    PROCEDURE SP_COMPLETE_SALESGOAL(P_SGL_ID IN TBL_SALESGOAL.SGL_ID%TYPE)
    IS
        V_STATE TBL_SALESGOAL.SGL_STATE%TYPE;
    BEGIN
    
        IF NOT(FN_SALESGOAL_EXIST(P_SGL_ID))THEN
            RAISE_APPLICATION_ERROR(-20603,'Meta no encontrada');
        END IF;

        SELECT SGL_STATE INTO V_STATE FROM TBL_SALESGOAL WHERE SGL_ID = P_SGL_ID;

        IF (LOWER(TRIM(V_STATE))IN('inactive','complete')) THEN
            RAISE_APPLICATION_ERROR(-20604,'Meta ya terminada o inactivada');
        END IF;

        UPDATE TBL_SALESGOAL SET SGL_STATE = 'complete' WHERE SGL_ID = P_SGL_ID;
    END SP_COMPLETE_SALESGOAL;

    FUNCTION FN_SALESGOAL_EXIST(P_SGL_ID IN TBL_SALESGOAL.SGL_ID%TYPE)
    RETURN BOOLEAN
    IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM TBL_SALESGOAL WHERE SGL_ID = P_SGL_ID;
        
        RETURN V_COUNT > 0;
        
    END FN_SALESGOAL_EXIST;

    FUNCTION FN_GET_SALESGOAL_BY_ID(P_SGL_ID IN TBL_SALESGOAL.SGL_ID%TYPE)
    RETURN TBL_SALESGOAL%ROWTYPE
    IS
        V_SALESGOAL TBL_SALESGOAL%ROWTYPE;
    BEGIN
        IF NOT(FN_SALESGOAL_EXIST(P_SGL_ID))THEN
            RAISE_APPLICATION_ERROR(-20603,'Meta no encontrada');
        END IF;

        SELECT * INTO V_SALESGOAL FROM TBL_SALESGOAL WHERE SGL_ID = P_SGL_ID;

    RETURN V_SALESGOAL;
    END FN_GET_SALESGOAL_BY_ID;

    FUNCTION FN_GET_ALL_SALESGOALS
    RETURN SYS_REFCURSOR
    IS
        V_SALESGOALS SYS_REFCURSOR;
    BEGIN
        OPEN V_SALESGOALS FOR
        SELECT * FROM TBL_SALESGOAL;
    RETURN V_SALESGOALS;

    END FN_GET_ALL_SALESGOALS;

    FUNCTION FN_GET_SALESGOALS_BY_STATE(P_SGL_STATE IN TBL_SALESGOAL.SGL_STATE%TYPE)
    RETURN SYS_REFCURSOR
    IS
        V_SALESGOALS SYS_REFCURSOR;
    BEGIN
        OPEN V_SALESGOALS FOR
        SELECT * FROM TBL_SALESGOAL WHERE LOWER(TRIM(SGL_STATE)) = LOWER(TRIM(P_SGL_STATE));

    RETURN V_SALESGOALS;
    END FN_GET_SALESGOALS_BY_STATE;

END PKG_SALESGOAL ;
/

CREATE OR REPLACE TRIGGER TRG_SALESGOAL_LOCK_COMPLETED
BEFORE UPDATE ON TBL_SALESGOAL
FOR EACH ROW
BEGIN
    IF (LOWER(TRIM(:OLD.SGL_STATE)) = 'complete') THEN
        RAISE_APPLICATION_ERROR(-20135,'No se puede modificar una meta ya completada');
    END IF;
END TRG_SALESGOAL_LOCK_COMPLETED;
/

CREATE OR REPLACE TRIGGER TRG_SALESGOAL_DATE_END
BEFORE INSERT OR UPDATE OF SGL_GOAL_TYPE, SGL_START_DATE
ON TBL_SALESGOAL
FOR EACH ROW
DECLARE
    V_DAYS_ELAPSED NUMBER;
BEGIN
    IF (LOWER(TRIM(:OLD.SGL_GOAL_TYPE)) = LOWER(TRIM(:NEW.SGL_GOAL_TYPE))) THEN
    RETURN;
    END IF;

    V_DAYS_ELAPSED := TRUNC(SYSDATE - :OLD.SGL_START_DATE);

    -- Validaciones de reducción inválida
    
    IF (LOWER(TRIM(:NEW.SGL_GOAL_TYPE)) = 'monthly' AND V_DAYS_ELAPSED > 30) THEN
        RAISE_APPLICATION_ERROR(-20620,'No se puede cambiar a monthly, la meta ya superó 30 días');
        
    ELSIF (LOWER(TRIM(:NEW.SGL_GOAL_TYPE)) = 'quarterly' AND V_DAYS_ELAPSED > 90) THEN
        RAISE_APPLICATION_ERROR(-20621,'No se puede cambiar a quarterly, la meta ya superó 90 días');
    END IF;


    -- Ajustar fecha final automáticamente

    IF (LOWER(TRIM(:NEW.SGL_GOAL_TYPE)) = 'monthly') THEN
        :NEW.SGL_END_DATE := :NEW.SGL_START_DATE + 30;

    ELSIF (LOWER(TRIM(:NEW.SGL_GOAL_TYPE)) = 'quarterly') THEN
        :NEW.SGL_END_DATE := :NEW.SGL_START_DATE + 90;

    ELSIF (LOWER(TRIM(:NEW.SGL_GOAL_TYPE)) = 'yearly') THEN
        :NEW.SGL_END_DATE := :NEW.SGL_START_DATE + 365;
    END IF;

END TRG_SALESGOAL_DATE_END;
/


/*======DICCIONARIO DE DATOS========*/
SELECT TABLE_NAME
FROM USER_TABLES
ORDER BY TABLE_NAME;
/*==================================*/
SELECT OBJECT_NAME, OBJECT_TYPE
FROM USER_OBJECTS
WHERE OBJECT_TYPE IN ('PROCEDURE','FUNCTION','PACKAGE','PACKAGE BODY')
ORDER BY OBJECT_TYPE, OBJECT_NAME;
/*==================================*/
SELECT OBJECT_NAME, PROCEDURE_NAME, OBJECT_TYPE
FROM USER_PROCEDURES
WHERE OBJECT_NAME = 'PKG_SALESGOAL'
ORDER BY PROCEDURE_NAME;