/*secuencia de generacion de id*/
CREATE SEQUENCE SEQ_SALE START WITH 7 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE PACKAGE PKG_SALE AS

    PROCEDURE SP_REGISTER_SALE(
        P_SALE_ID           OUT TBL_SALE.SALE_ID%TYPE,
        P_CUS_ID            IN TBL_SALE.CUS_ID%TYPE,
        P_EMP_ID            IN TBL_SALE.EMP_ID%TYPE,
        P_UNIT_ID            IN TBL_SALE.UNIT_ID%TYPE,
        P_SALE_PRICE        IN TBL_SALE.SALE_PRICE%TYPE
    );

    PROCEDURE SP_REGISTER_RESERVATION(
        P_SALE_ID           OUT TBL_SALE.SALE_ID%TYPE,
        P_CUS_ID            IN TBL_SALE.CUS_ID%TYPE,
        P_EMP_ID            IN TBL_SALE.EMP_ID%TYPE,
        P_UNIT_ID            IN TBL_SALE.UNIT_ID%TYPE,
        P_SALE_PRICE        IN TBL_SALE.SALE_PRICE%TYPE,
        P_SALE_DATE_END     IN TBL_SALE.SALE_DATE_END%TYPE DEFAULT NULL
    );

    PROCEDURE SP_COMPLETE_RESERVATION(P_SALE_ID IN TBL_SALE.SALE_ID%TYPE);

    PROCEDURE SP_CANCEL_RESERVATION(P_SALE_ID IN TBL_SALE.SALE_ID%TYPE);

    FUNCTION FN_SALE_EXIST(P_SALE_ID IN TBL_SALE.SALE_ID%TYPE)
    RETURN BOOLEAN;

    FUNCTION FN_GET_SALE_BY_ID(P_SALE_ID IN TBL_SALE.SALE_ID%TYPE)
    RETURN TBL_SALE%ROWTYPE;

    FUNCTION FN_GET_ALL_SALES
    RETURN SYS_REFCURSOR;
    
    FUNCTION FN_GET_SALES_BY_STATUS(P_SALE_STATUS IN VARCHAR2)
    RETURN SYS_REFCURSOR;

END PKG_SALE;
/

CREATE OR REPLACE PACKAGE BODY PKG_SALE AS
    PROCEDURE SP_REGISTER_SALE(
        P_SALE_ID           OUT TBL_SALE.SALE_ID%TYPE,
        P_CUS_ID            IN TBL_SALE.CUS_ID%TYPE,
        P_EMP_ID            IN TBL_SALE.EMP_ID%TYPE,
        P_UNIT_ID            IN TBL_SALE.UNIT_ID%TYPE,
        P_SALE_PRICE        IN TBL_SALE.SALE_PRICE%TYPE
    )
    IS
        V_COUNT NUMBER;
        V_UNIT_STATUS TBL_UNIT.UNIT_STATUS%TYPE;
    BEGIN
        
        IF NOT(PKG_EMPLOYEE.FN_EMPLOYEE_EXIST(P_EMP_ID))THEN
            RAISE_APPLICATION_ERROR(-20710,'Empleado no encontrado');
        END IF;
        
        IF NOT(PKG_CUSTOMER.FN_CUSTOMER_EXIST(P_CUS_ID))THEN
            RAISE_APPLICATION_ERROR(-20709,'Cliente no encontrado');
        END IF;
        
        SELECT COUNT(*) INTO V_COUNT FROM TBL_SALE WHERE CUS_ID = P_CUS_ID AND LOWER(TRIM(SALE_STATUS))='inprogress';
        IF(V_COUNT>0)THEN
            RAISE_APPLICATION_ERROR(-20702,'El cliente ya tiene una reserva activa');
        END IF;
        
        IF NOT(PKG_UNIT.FN_UNIT_EXIST(P_UNIT_ID))THEN
            RAISE_APPLICATION_ERROR(-20708,'Unidad no encontrada');
        END IF;
        
        SELECT UNIT_STATUS INTO V_UNIT_STATUS FROM TBL_UNIT WHERE UNIT_ID = P_UNIT_ID;
        IF(LOWER(TRIM(V_UNIT_STATUS)) <> 'available')THEN
            RAISE_APPLICATION_ERROR(-20707,'La unidad no está disponible');
        END IF;
        
        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_SALE_PRICE,'P_SALE_PRICE');
        
        INSERT INTO TBL_SALE (SALE_ID,CUS_ID,EMP_ID,UNIT_ID,SALE_DATE_START,SALE_PRICE,SALE_STATUS,SALE_DATE_END)
        VALUES (SEQ_SALE.NEXTVAL,P_CUS_ID,P_EMP_ID,P_UNIT_ID,SYSDATE,P_SALE_PRICE,'confirmed',SYSDATE) RETURNING SALE_ID INTO P_SALE_ID;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR(-20900,'Violacion de PK o UNIQUE.');
    END SP_REGISTER_SALE;

    PROCEDURE SP_REGISTER_RESERVATION(
        P_SALE_ID           OUT TBL_SALE.SALE_ID%TYPE,
        P_CUS_ID            IN TBL_SALE.CUS_ID%TYPE,
        P_EMP_ID            IN TBL_SALE.EMP_ID%TYPE,
        P_UNIT_ID            IN TBL_SALE.UNIT_ID%TYPE,
        P_SALE_PRICE        IN TBL_SALE.SALE_PRICE%TYPE,
        P_SALE_DATE_END     IN TBL_SALE.SALE_DATE_END%TYPE DEFAULT NULL
    )
     IS
        V_COUNT NUMBER;
        V_UNIT_STATUS TBL_UNIT.UNIT_STATUS%TYPE;
    BEGIN
        
        IF NOT(PKG_EMPLOYEE.FN_EMPLOYEE_EXIST(P_EMP_ID))THEN
            RAISE_APPLICATION_ERROR(-20710,'Empleado no encontrado');
        END IF;
        
        IF NOT(PKG_CUSTOMER.FN_CUSTOMER_EXIST(P_CUS_ID))THEN
            RAISE_APPLICATION_ERROR(-20709,'Cliente no encontrado');
        END IF;
        
        SELECT COUNT(*) INTO V_COUNT FROM TBL_SALE WHERE CUS_ID = P_CUS_ID AND LOWER(TRIM(SALE_STATUS))='inprogress';
        IF(V_COUNT>0)THEN
            RAISE_APPLICATION_ERROR(-20702,'El cliente ya tiene una reserva activa');
        END IF;
        
        IF NOT(PKG_UNIT.FN_UNIT_EXIST(P_UNIT_ID))THEN
            RAISE_APPLICATION_ERROR(-20708,'Unidad no encontrada');
        END IF;
        
        SELECT UNIT_STATUS INTO V_UNIT_STATUS FROM TBL_UNIT WHERE UNIT_ID = P_UNIT_ID;
        IF(LOWER(TRIM(V_UNIT_STATUS)) <> 'available')THEN
            RAISE_APPLICATION_ERROR(-20707,'La unidad no está disponible');
        END IF;
        
        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_SALE_PRICE,'P_SALE_PRICE');
        PKG_VALIDATIONS.VALIDATE_DATE_RANGE(SYSDATE,P_SALE_DATE_END);
        
        --Trigger encargado demoddificar el estado de unidad
        
        INSERT INTO TBL_SALE (SALE_ID,CUS_ID,EMP_ID,UNIT_ID,SALE_DATE_START,SALE_PRICE,SALE_STATUS,SALE_DATE_END)
        VALUES (SEQ_SALE.NEXTVAL,P_CUS_ID,P_EMP_ID,P_UNIT_ID,SYSDATE,P_SALE_PRICE,'inprogress',P_SALE_DATE_END) RETURNING SALE_ID INTO P_SALE_ID;
        
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR(-20900,'Violacion de PK o UNIQUE.');
        
    END SP_REGISTER_RESERVATION;

    PROCEDURE SP_COMPLETE_RESERVATION(P_SALE_ID IN TBL_SALE.SALE_ID%TYPE)
    IS
        V_CURRENT_STATE TBL_SALE.SALE_STATUS%TYPE;
    BEGIN
        IF NOT(FN_SALE_EXIST(P_SALE_ID))THEN
            RAISE_APPLICATION_ERROR(-20701,'Venta no encontrada');
        END IF;
        
        SELECT SALE_STATUS INTO V_CURRENT_STATE FROM TBL_SALE WHERE SALE_ID = P_SALE_ID;
        IF (LOWER(TRIM(V_CURRENT_STATE)) = 'confirmed') THEN
            RAISE_APPLICATION_ERROR(-20703,'La reserva ya ha sido confirmada');
        END IF;
        IF (LOWER(TRIM(V_CURRENT_STATE)) = 'cancelled') THEN
            RAISE_APPLICATION_ERROR(-20704,'La reserva ha sido cancelada');
        END IF;
        
        --Trigger encargado de moificar estado de unidad
        
        UPDATE TBL_SALE SET SALE_STATUS = 'confirmed', SALE_DATE_END = SYSDATE WHERE SALE_ID = P_SALE_ID;
        
    END SP_COMPLETE_RESERVATION;

    PROCEDURE SP_CANCEL_RESERVATION(P_SALE_ID IN TBL_SALE.SALE_ID%TYPE)
    IS
        V_CURRENT_STATE TBL_SALE.SALE_STATUS%TYPE;
    BEGIN

        IF NOT(FN_SALE_EXIST(P_SALE_ID))THEN
            RAISE_APPLICATION_ERROR(-20701,'Venta no encontrada');
        END IF;
        
        SELECT SALE_STATUS INTO V_CURRENT_STATE FROM TBL_SALE WHERE SALE_ID = P_SALE_ID;
        IF (LOWER(TRIM(V_CURRENT_STATE)) = 'cancelled') THEN
            RAISE_APPLICATION_ERROR(-20703,'La reserva ya ha sido cancelada');
        END IF;
        
        IF (LOWER(TRIM(V_CURRENT_STATE)) = 'confirmed') THEN
            RAISE_APPLICATION_ERROR(-20704,'La reserva ya ha sido completada');
        END IF;
        
        --Trigger encargado de moificar estado de unidad
        
        UPDATE TBL_SALE SET SALE_STATUS = 'cancelled' WHERE SALE_ID = P_SALE_ID;
        UPDATE TBL_SALE SET SALE_DATE_END = SYSDATE WHERE SALE_ID = P_SALE_ID;
    END SP_CANCEL_RESERVATION; 

    FUNCTION FN_SALE_EXIST(P_SALE_ID IN TBL_SALE.SALE_ID%TYPE)
    RETURN BOOLEAN
    IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM TBL_SALE WHERE SALE_ID = P_SALE_ID;
        
        RETURN V_COUNT>0;
    END FN_SALE_EXIST;

    FUNCTION FN_GET_SALE_BY_ID(P_SALE_ID IN TBL_SALE.SALE_ID%TYPE)
    RETURN TBL_SALE%ROWTYPE
    IS
        V_SALE TBL_SALE%ROWTYPE;
    BEGIN

        IF NOT(FN_SALE_EXIST(P_SALE_ID))THEN
            RAISE_APPLICATION_ERROR(-20805,'Venta no encontrada');
        END IF;
        
        SELECT * INTO V_SALE FROM TBL_SALE WHERE SALE_ID = P_SALE_ID;
        
    RETURN V_SALE;
    END FN_GET_SALE_BY_ID;

    FUNCTION FN_GET_ALL_SALES
    RETURN SYS_REFCURSOR
    IS
    V_SALES SYS_REFCURSOR;

    BEGIN

        OPEN V_SALES FOR
        SELECT * FROM TBL_SALE;

    RETURN V_SALES;
    END FN_GET_ALL_SALES;
    
    FUNCTION FN_GET_SALES_BY_STATUS (P_SALE_STATUS IN VARCHAR2)
     RETURN SYS_REFCURSOR
    IS
    V_SALES SYS_REFCURSOR;

    BEGIN
        PKG_VALIDATIONS.VALIDATE_SALE_STATUS(P_SALE_STATUS);
        
        OPEN V_SALES FOR
        SELECT * FROM TBL_SALE WHERE LOWER(TRIM(SALE_STATUS)) = LOWER(TRIM(P_SALE_STATUS));

    RETURN V_SALES;
    END FN_GET_SALES_BY_STATUS;
    
END PKG_SALE;
/

CREATE OR REPLACE TRIGGER TRG_UPDATE_UNIT_STATUS_BY_SALE
AFTER INSERT OR UPDATE OF SALE_STATUS ON TBL_SALE
FOR EACH ROW
BEGIN

    IF LOWER(TRIM(:NEW.SALE_STATUS)) = 'confirmed' THEN

        UPDATE TBL_UNIT SET UNIT_STATUS = 'sold' WHERE UNIT_ID = :NEW.UNIT_ID;

    ELSIF LOWER(TRIM(:NEW.SALE_STATUS)) = 'cancelled' THEN

        UPDATE TBL_UNIT SET UNIT_STATUS = 'available' WHERE UNIT_ID = :NEW.UNIT_ID;

    ELSIF LOWER(TRIM(:NEW.SALE_STATUS)) = 'inprogress' THEN

        UPDATE TBL_UNIT SET UNIT_STATUS = 'reserved' WHERE UNIT_ID = :NEW.UNIT_ID;

    END IF;

END TRG_UPDATE_UNIT_STATUS_BY_SALE;
/

CREATE OR REPLACE TRIGGER TRG_PROTECTED_SALE
BEFORE DELETE ON TBL_SALE
BEGIN
    RAISE_APPLICATION_ERROR(-20135,'No se pueden eliminar datos de esta tabla');
END TRG_PROTECTED_SALE;
/

CREATE OR REPLACE TRIGGER TRG_UPDATE_UNIT_STATUS
BEFORE UPDATE OF UNIT_STATUS ON TBL_UNIT
FOR EACH ROW
BEGIN
    IF LOWER(TRIM(:OLD.UNIT_STATUS)) = 'sold' AND LOWER(TRIM(:NEW.UNIT_STATUS)) IN ('available','reserved') THEN
        RAISE_APPLICATION_ERROR(-20135,'Una unidad vendida no puede volver a estar disponible o reservada');
    END IF;
END TRG_UPDATE_UNIT_STATUS;
/

CREATE OR REPLACE VIEW VW_SALES_REPORT AS
SELECT
    S.SALE_ID,
    S.SALE_DATE_START,
    S.SALE_DATE_END,
    S.SALE_PRICE,
    S.SALE_STATUS,
    C.CUS_NAME,
    E.EMP_NAME,
    U.UNIT_LICENSE_PLATE,
    V.VEH_BRAND,
    V.VEH_MODEL
FROM TBL_SALE S
JOIN TBL_CUSTOMER C ON C.CUS_ID = S.CUS_ID
JOIN TBL_EMPLOYEE E ON E.EMP_ID = S.EMP_ID
JOIN TBL_UNIT U ON U.UNIT_ID = S.UNIT_ID
JOIN TBL_VEHICLE V ON V.VEH_ID = U.VEH_ID;

